APP-611 origin check multiple ips
robson-sanchez/App-Integrations-Commons pull request #1
Opened 2017-01-26 18:15 UTC by ecarrenho-daitan

Support multiple IP's on the x-forwarded-for header.

This PR is just adding new support on the log message formatter to allow logging messages with a single solution passed as string instead of single item collection.

2017-01-27 16:06 UTC, robson-sanchez approved these changes
Minor changes to simplify the code.

2017-01-27 16:06 UTC, rsanchez-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/exception/ExceptionMessageFormatter.java
> +    return getMessage(component, message, solutions, null);
Could we use varargs parameters insteadof a list of strings?

Something like that: getMessage(String component, String message, Throwable t, String... solutions)

2017-01-31 21:08 UTC, ecarrenho-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/exception/ExceptionMessageFormatter.java
> +    return getMessage(component, message, solutions, null);
Done

2017-01-31 23:50 UTC, dnsymphony requested changes

2017-01-31 23:50 UTC, dnsymphony commented on integration-commons/src/main/java/org/symphonyoss/integration/logging/LogMessageSource.java
> +  private static final String UNABLE_TO_LOAD_LOG_MESSAGES_SOLUTION1 =
What's the '1' for?

2017-01-31 23:50 UTC, dnsymphony commented on integration-commons/src/main/java/org/symphonyoss/integration/logging/LogMessageSource.java
> +      return UNABLE_TO_RECORD_LOG_INFORMATION_LOG_MESSAGE_NOT_FOUND;
This should include the resource ID and the args.

2017-01-31 23:50 UTC, dnsymphony commented on integration-commons/src/test/java/org/symphonyoss/integration/logging/LogMessageSourceTest.java
> +    assertEquals("Unable to load log messages from log-messages.properties files. "
This is testing the text in the resource bundle in the test directory (which right now is a copy of the one in src directory.  But if someone changes that one, this test will still pass.  Is that expected?

2017-02-01 11:08 UTC, ecarrenho-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/logging/LogMessageSource.java
> +  private static final String UNABLE_TO_LOAD_LOG_MESSAGES_SOLUTION1 =
Will remove it, I was numbering solutions as they might have been multiple, but it ended up being weird.

2017-02-01 11:09 UTC, ecarrenho-daitan commented on integration-commons/src/test/java/org/symphonyoss/integration/logging/LogMessageSourceTest.java
> +    assertEquals("Unable to load log messages from log-messages.properties files. "
Yes, it is expected. We are testing the code that accesses resources not the resources themselves.

2017-02-01 12:03 UTC, ecarrenho-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/logging/LogMessageSource.java
> +      return UNABLE_TO_RECORD_LOG_INFORMATION_LOG_MESSAGE_NOT_FOUND;
Done.

2017-02-01 13:43 UTC, merged